### ISSUE TITLE
Error on creating Storybook using --storybook option

### ISSUE THREAD

**Issue by Dushyant099** [mb3online/speck#15]
| => speck -i src -t js,jsx --storybook
[12:28:43:29]: Starting parse.
[12:28:43:30]: Parsing /private/tmp/src/test.jsx ✓
[12:28:43:30]: Reading /private/tmp/src/test.jsx ✓
{ name: 'TextInput',
  extends: '',
  type: 'Input',
  description: 'Enables you to type in.',
  props: { id: { default: 25, type: 'number', description: 'test description' } },
  'sub-components': [],
  usage: { jsx: '<TextInput ...props />' },
  interactions:
   [ 'can render to the page',
     'can work when i tell it to',
     'can Make new line' ] }
[12:28:43:36]: Parsing /private/tmp/src/test.spec.jsx ✓
(node:78831) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): SyntaxError: Unexpected token (18:3)

**Comment by ericadamski** [comment]
`(node:78831) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): SyntaxError: Unexpected token (18:3)` Looks to be an issue with tabs vs spaces.

**Comment by ericadamski** [comment]
Cannot recreat.

**Comment by ericadamski** [comment]
Remove this feature see #73
