### ISSUE TITLE
.spec file needs updates based on coding conventions

### ISSUE THREAD

**Issue by devriestyler** [mb3online/speck#47]
![screen shot 2016-10-06 at 3 28 28 pm](https://cloud.githubusercontent.com/assets/12612075/19167438/bb78228e-8bd9-11e6-8a44-10a5d26a5f82.png)

This needs spaces in the brackets to resolve code convention conflicts in the future when generating .spec.jsx files

**Comment by pvienneau** [comment]
See PR #46.

**Comment by devriestyler** [comment]
This was updated in another issue
