### ISSUE TITLE
Speck file generating incorrect file path to mb3 components

### ISSUE THREAD

**Issue by devriestyler** [mb3online/speck#48]
![screen shot 2016-10-07 at 2 39 16 pm](https://cloud.githubusercontent.com/assets/12612075/19201410/b4dd9cb6-8c9b-11e6-96d0-56f0a1163790.png)

Spec file being generated from Speck is generating an incorrect file path for the newly created component. Easy to resolve by manually changing this, however testing fails immediately and may not be the first thing someone checks after generating their spec file

**Comment by ericadamski** [comment]
This is most likely due to the naming convention change. If this is more than that, ie. that relative path goes to the wrong folder this could be more of on issue.

**Comment by ericadamski** [comment]
@devriestyler what was the command that you ran to get this?

**Comment by ericadamski** [comment]
[This line](https://github.com/mb3online/speck/blob/develop/src/plugins/jest.plugin.js#L139) is probably the issue
