### ISSUE TITLE
Solution for components with multiple sections of properties for sub-components

### ISSUE THREAD

**Issue by devriestyler** [mb3online/speck#52]
![screen shot 2016-10-11 at 10 18 15 am](https://cloud.githubusercontent.com/assets/12612075/19273773/d1431b6c-8f9b-11e6-9828-10609cb3e5d9.png)

For Components with multiple sub-components and properties speck should be updated to generate sub-headings for each section.

**Comment by ericadamski** [comment]
This has nothing todo with speck, it is more a doc site thing.

**Comment by pvienneau** [comment]
Moved to [MB3/docs], see issue [#47](https://github.com/mb3online/docs/issues/76).
