### ISSUE TITLE
Allow minimatch and directory search

### ISSUE THREAD

**Issue by frytyler** [mb3online/speck#59]
Would be great to have a speck.js file in the root of a project that could define things like: 
- ignored file patterns eg. `*.blade.php` 
- directories to check eg. `app, tests, database, routes`

**Comment by frytyler** [comment]
@ericadamski What's the starting point here? Somewhere I can jump in and start messing around or better to wait for a walk through?

**Comment by ericadamski** [comment]
[To get the path](https://nodejs.org/api/process.html#process_process_cwd)
